#if !defined(_acorn_h_)

#define _acorn_h_

#include "version.h"

#define RETURN_NO_ERROR 0
#define RETURN_ERROR -1
#define RETURN_AFFIRMATIVE 1
#define RETURN_NIL -2147483648 
#define RETURN_NO_CONNECTION -2147483647

#define DEBUG_LEVEL_MANDATORY_NON_ERROR -1
#define DEBUG_LEVEL_BASIC_INFORMATIVE 1
#define DEBUG_LEVEL_BASIC_LESS_INFORMATIVE 2
#define DEBUG_LEVEL_SOMEWHAT_NOISY_INFORMATIVE 3
#define DEBUG_LEVEL_MORE_NOISY_INFORMATIVE 4
#define DEBUG_LEVEL_FREQUENT_NOISY 10
#define DEBUG_LEVEL_CRAZY_VERBOSE 15
#define DEBUG_LEVEL_STDERR 255


#endif //!defined(_acorn_h_)