#if !defined(_acorn_h_)

#define _acorn_h_

#define RETURN_NO_ERROR 0
#define RETURN_ERROR -1
#define RETURN_AFFIRMATIVE 1
#define RETURN_NIL -2147483648 

#define DEBUG_LEVEL_BASIC_INFORMATIVE 1
#define DEBUG_LEVEL_SOMEWHAT_NOISY_INFORMATIVE 3
#define DEBUG_LEVEL_FREQUENT_NOISY 10
#define DEBUG_LEVEL_CRAZY_VERBOSE 15
#define DEBUG_LEVEL_STDERR 255

#define DO_CMD_NOT_SILENT 0
#define DO_CMD_SILENT 1

#endif //!defined(_acorn_h_)