#!/bin/bash
F=$@
WORKING_DIRECTORY=`pwd`


if [[ $F = "" ]]; then
	F="acorn"
fi

if [ -e ./release_notes.txt ]; then
  echo -e "\r\n\r\n"
	cat ./release_notes.txt
fi

if [ "$F" != "acorn" ]; then
  echo "compiling $F in $WORKING_DIRECTORY"
else
  VERSION=`grep VER acorn.h|awk 'FNR==1{print $4}'|sed -e 's/"//g'`
  echo "compiling $F version $VERSION in $WORKING_DIRECTORY"
fi

gcc -g -o $F $F.c ini.c
